#!/system/bin/sh

function RandomLogcat() {
	log -p i -t "RandomKernel" $1;
}

# Fixing Permissinos for LMK
RandomLogcat "Fixing permissions...";
for i in `seq 0 3`; do
	chmod 644 /sys/devices/system/cpu/cpu$i/online;
done;

# Setting Governor on Boot
RandomLogcat "Setting CPU parameters (governor)...";
for i in `seq 0 3`; do
	echo "blu_active" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor;
done;

# Changing Governor Values
RandomLogcat "Setting CPU parameters (governor settings)...";
echo "19000 1248000:29000" > /sys/devices/system/cpu/cpufreq/blu_active/above_hispeed_delay;
echo "85" > /sys/devices/system/cpu/cpufreq/blu_active/go_hispeed_load;
echo "1248000" > /sys/devices/system/cpu/cpufreq/blu_active/hispeed_freq;
echo "85 1248000:80" > /sys/devices/system/cpu/cpufreq/blu_active/target_loads;
echo "30000" > /sys/devices/system/cpu/cpufreq/blu_active/timer_rate;
echo "60000" > /sys/devices/system/cpu/cpufreq/blu_active/timer_slack;

# Enabling MSM Limiter
RandomLogcat "Setting CPU parameters (MSM Limiter)...";
echo "1" > /sys/kernel/msm_limiter/limiter_enabled;

# Enabling Simple Thermal Driver
RandomLogcat "Enabling Simple Thermal...";
echo "1" > /sys/kernel/msm_thermal/enabled;
